services:
  db:
    image: pgvector/pgvector:pg16
    container_name: grant_finder_db
    ports:
      - "5440:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: grant_finder
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    container_name: grant_finder_redis
    ports:
      - "6379:6379"

volumes:
  postgres_data:
